### PR TITLE
Fix command verify logic

### PR DESCRIPTION
**Pull request by rahul-raturi**
- Pass the command string to `commandExists` method.
- Using dot operator to check whether the object has that attribute or
  not won't work as `command` is a string.

### CODE REVIEW

**Comment by sagarkarira** [comment]
Can you do this in **utils.js** ?
`
if (cmdcfg[command]) {
  return true;
}
return false;
`
Although your logic is correct. But this is better to understand.

**Comment by rahul-raturi** [comment]
@sagarkarira, can you re-open it. I'll push the suggested changes to it. It doesn't makes much sense to create a new PR for the same context.

**Comment by sagarkarira** [comment]
@rahul-raturi  Here you go .

**Comment by rahul-raturi** [comment]
@sagarkarira, have a look now. I think `in` operator is more logical for checking an existing key.

**Comment by sagarkarira** [comment]
@rahul-raturi Yup, seems good.

**Pull request merged**
